import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Squares from "@/background/Squares/Squares";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Form Element",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        
        <div className="fixed top-0 left-0 w-full h-full -z-10">
          <Squares 
            speed={0.35} 
            squareSize={50}
            direction="diagonal"
            borderColor="rgb(34,34,34)"
            hoverFillColor="#222"
          />
        </div>

      

        <main className="relative">{children}</main>

      </body>
    </html>
  );
}
